version: '3.8'
services:
  nginx:
    build:
      context: .
    container_name: nginx
    volumes:
      - ./demo:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/self.crt:/etc/nginx/ssl/self.crt
      - ./ssl/self.key:/etc/nginx/ssl/self.key
      - ./ssl/dhparam.pem:/etc/nginx/ssl/dhparam.pem
      - ./auth/.htpasswd:/etc/nginx/.htpasswd
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
      - '443:443'
    links:
      - web
  web:
    image: php:fpm
    container_name: nginx_php_fpm
    volumes:
      - ./demo:/usr/share/nginx/html
